[package]
name = "woodstock"
version = "0.1.0"
edition = "2021"

authors = [
    "Mihael Berčič <mihael.bercic@innorenew.eu>",
    "Domen Vake <domen.vake@innorenew.eu>",
]

[dependencies]
actix-web = "4.9.0"
actix-multipart = "0.7.2"
