[package]
name = "woodstock"
version = "0.1.0"
edition = "2021"

authors = [
    "Mihael Berčič <mihael.bercic@innorenew.eu>",
    "Domen Vake <domen.vake@innorenew.eu>",
]

[dependencies]
actix-web-lab = { version = "0.23.0", features = ["spa"] }
actix-web = "4.9.0"
actix-multipart = "0.7.2"
actix-files = "0.6.6"
actix-cors = "0.7.0"
ollama-rs = "0.2.3"
anyhow = "1.0.95"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
serde = { version = "1.0.217", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
serde_json = "1.0.135"
lopdf = { version = "0.30.0", features = ["pom", "pom_parser"] }
# postgres = { version = "0.19.9" }
tokio-postgres = "*"
uuid = { version = "1.12.0", features = ["v4"] }
